on:
  push:
    branches: [master]

jobs:
  build_pages:
      #needs: create_pages
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout code
          uses: actions/checkout@v3

        - name: build with jekyll
          uses: actions/jekyll-build-pages@v1
          with: 
            source: .
            destination: ./_site
            future: false
            verbose: true

        - name: uplaod pages artifact
          uses: actions/upload-pages-artifact@v1
          with:
            path: ./_site
            name: github-pages
            retention-days: 1

        - name: report build status
          env: 
            GH_TOKEN: ${{ github.token }}
          run: |
            gh api -X POST "repos/$GITHUB_REPOSITORY/pages/telemetry" \
            -F github_run_id="$GITHUB_RUN_ID" \
            -F conclusion="$CONCLUSION"

  deploy_pages:
    needs: build_pages
    runs-on: ubuntu-latest
    permissions:
        pages: write
        id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
        - name: deploy pages
          uses: actions/deploy-pages@v1
          with:
            #emit_telemetry: false
            timeout: 600000
            error_count: 10
            reporting_interval: 5000
            artifact_name: github-pages
            preview: false